---

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  test:

services:

  prometheus:
    image: prom/prometheus:v2.48.0
    logging:
      driver: local
      options:
        max-size: 10m
    depends_on:
      - vector
    networks:
      - test
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - ./.compose/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus

  loki:
    image: grafana/loki:3.6.5
    command: -config.file=/etc/loki/local-config.yaml
    logging:
      driver: local
      options:
        max-size: 10m
    networks:
      - test

  grafana:
    image: grafana/grafana:9.5.14
    user: "472"
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    networks:
      - test
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: false
    logging:
      driver: local
      options:
        max-size: 10m
    volumes:
      - grafana_data:/var/lib/grafana
      - ./.compose/grafana/provisioning/:/etc/grafana/provisioning/

  nginx:
    image: dhi.io/nginx:1.29.6-debian13
    read_only: true
    labels:
      application: Baywatch
    logging:
      driver: json-file
      options:
        labels: application
        tag: id={{.ID}} name={{.Name}} image={{.ImageName}}
    ports:
      - '8083:80'
    networks:
      - test
    tmpfs:
      - /run/nginx:exec,mode=777,uid=1000,gid=1000
      - /var/cache/nginx:exec,mode=777,uid=1000,gid=1000
    volumes:
      - ./.compose/nginx/conf.d:/etc/nginx/conf.d:ro

  vector:
    image: dhi.io/vector:0.54.0-debian13-dev
    command: ['--config', '/etc/vector/vector.yaml']
    user: '0:0'
    read_only: true
    depends_on:
      - loki
    logging:
      driver: local
      options:
        max-size: 10m
    tmpfs:
      - /var/lib/vector:exec
    volumes:
      - ./.compose/vector/vector.yaml:/etc/vector/vector.yaml:ro
      - /home/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro,rslave
      - ./.compose/vector/GeoLite2-City.mmdb:/var/lib/geoip/GeoLite2-City.mmdb:ro
    networks:
      - test

#  opentelemetry:
#    image: otel/opentelemetry-collector-contrib:0.89.0
#    user: '0:0'
#    ports:
#      - '4317:4317'
#      - '4318:4318'
#      - '9091:9091'
#    command:
#      - '--config=/etc/otel/service.yaml'
#    logging:
#      driver: local
#      options:
#        max-size: 10m
#    networks:
#      - test
#    volumes:
#      - './.compose/otel:/etc/otel:ro'
