{
 "title": "Otela",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "site", "query": { "query": "label_values(service_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Dernières Visites",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(otela_calls_total{service_name=\"$site\"}[$__rate_interval]))",
     "legendFormat": "Visites"
    }
   ]
  },
  {
   "title": "Total Visites",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(otela_calls_total{service_name=\"$site\"}[${__range}]@${__to:date:seconds})))"
    }
   ]
  },
  {
   "title": "Visiteurs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  group(\n    count_over_time(otela_calls_total{service_name=\"$site\"}[$__interval])\n  ) by (ip)\n)"
    }
   ]
  },
  {
   "title": "Referrer",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by(referrer) (increase(otela_calls_total{service_name=\"$site\"}[$__range]))!=0)",
     "legendFormat": "{{referrer}}"
    }
   ]
  },
  {
   "title": "Par Page",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by(span_name) (increase(otela_calls_total{service_name=\"$site\"}[$__range]))!=0)",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}