gzip             on;
gzip_disable     "msie6"; 
gzip_vary        on;

gzip_comp_level  6; # 1 par défaut (le plus bas), 9 étant le plus élevé
gzip_min_length  256; # taille minimale du fichier à compresser
gzip_proxied     any;
gzip_types       text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/rss+xml text/javascript application/vnd.ms-fontobject application/x-font-ttf font/opentype image/jpeg image/png image/svg+xml image/x-icon; 
