server {
    listen 80 default_server;
	listen [::]:80 default_server;
	server_name _;
    http2   on;

    location /v1/traces {
        limit_except GET { deny all; }
        return 200 'gangnam style!';
    }
}
